name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --component clippy,rustfmt --target wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --target wasm32-unknown-unknown --all-targets -- -D warnings

      - name: Test
        run: cargo test

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.1
        with:
          version: latest

      - name: Build (release)
        run: trunk build --release
